# Практическая работа 1-1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [4]:
import numpy as np

np.version.version

'1.23.5'

2) Создать нулевой вектор размера 10

In [8]:
vector = np.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [7]:
vector = np.full((7,), 7)
vector

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [10]:
start = 10
end = 101
step = 2

vector = np.arange(start, end, step)

vector

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [11]:
import numpy as np
import random

array_size = 10  # Задаем размер массива
random_numbers = np.random.randint(0, 19, size=array_size)
print("Случайные числа: ", random_numbers)

Случайные числа:  [ 6  1 13  2 14  2 15  0 10 18]


In [12]:
reversed_numbers = random_numbers[::-1]
print("Развернутый массив: ", reversed_numbers)

Развернутый массив:  [18 10  0 15  2 14  2 13  1  6]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [13]:
matrix = np.array([[x for x in range(0,10)] for y in range(0,3)])
print(matrix)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [46]:
matrix = np.eye(4, 4)
matrix = matrix.tolist()

In [47]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [69]:
matrix=np.full((4, 4), 7) - np.diag([6,5,4,3])

In [70]:
result = np.array(matrix)
print(result)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [72]:
matrix = np.array([[x for x in range(0,5)] for y in range(0,5)])
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [125]:
matrix = [[random.randint(1, 100) for _ in range(10)] for _ in range(10)]

In [126]:
for row in matrix:
    average = sum(row) / len(row)
    row[:] = [num - average for num in row]

In [127]:
for row in matrix:
    print(row)

[-11.3, -17.3, 15.7, -24.3, -8.3, -12.3, 32.7, 21.7, 25.7, -22.3]
[-27.5, -38.5, 54.5, 7.5, -34.5, 33.5, -16.5, -30.5, 19.5, 32.5]
[-15.299999999999997, -23.299999999999997, 23.700000000000003, 45.7, 21.700000000000003, -17.299999999999997, -36.3, 41.7, -13.299999999999997, -27.299999999999997]
[13.100000000000001, 0.10000000000000142, -14.899999999999999, -2.8999999999999986, -10.899999999999999, -28.9, 34.1, 43.1, 2.1000000000000014, -34.9]
[-32.7, -1.7000000000000028, 9.299999999999997, 3.299999999999997, -7.700000000000003, 17.299999999999997, 22.299999999999997, -10.700000000000003, -9.700000000000003, 10.299999999999997]
[-18.0, -37.0, -29.0, 31.0, 33.0, 19.0, -11.0, 2.0, 17.0, -7.0]
[52.3, -10.700000000000003, -10.700000000000003, 34.3, -6.700000000000003, -12.700000000000003, -36.7, -2.700000000000003, -7.700000000000003, 1.2999999999999972]
[-12.600000000000001, -10.600000000000001, 17.4, -1.6000000000000014, -12.600000000000001, 11.399999999999999, -49.6, 32.4, 31.4, -5.60000

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [128]:
matrix = np.random.randint(1, 100, size=(10, 10))

In [129]:
medians = np.median(matrix, axis=0)
matrix = matrix - medians

In [130]:
print(matrix)

[[-16.5   0.   54.   24.5 -10.   48.5 -22.   36.5 -30.5   0. ]
 [ 20.5 -58.   48.  -51.5  -3.   -7.5 -27.   16.5 -25.5   0. ]
 [-24.5  17.   68.   -8.5 -37.  -45.5  18.   30.5   0.5  14. ]
 [-32.5  32.   54.   16.5  21.  -28.5  -3.    1.5  33.5 -52. ]
 [-26.5  15.   11.   22.5   3.   15.5   3.  -17.5  38.5  12. ]
 [ 18.5 -47.  -15.  -20.5 -39.   38.5  39.   -1.5  -0.5   6. ]
 [ 14.5 -21.  -15.  -44.5  30.   34.5  56.  -51.5 -46.5  -3. ]
 [ -1.5   0.  -11.   30.5  53.  -26.5   6.   16.5  19.5  -1. ]
 [ 22.5 -11.  -16.    8.5 -10.   -6.5  -7.  -52.5 -24.5  28. ]
 [  1.5   3.  -18.  -35.5  17.    6.5 -13.  -53.5   9.5 -60. ]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [131]:
matrix = np.random.randint(1, 100, size=(5, 5))

In [132]:
max_values = np.max(matrix, axis=1)
matrix_with_max = np.column_stack((matrix, max_values))

In [133]:
min_values = np.min(matrix, axis=1)
matrix_with_min_and_max = np.column_stack((matrix_with_max, min_values))

In [134]:
print(matrix_with_min_and_max)

[[62 71 31 91 69 91 31]
 [63 15 23 55 33 63 15]
 [ 1  8 32 66 51 66  1]
 [83 85 78 81 23 85 23]
 [75 13  8 30 36 75  8]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [216]:
numbers = np.arange(1, 51)

In [217]:
odd_numbers = numbers[numbers % 2 != 0]
even_numbers = numbers[numbers % 2 == 0]

In [218]:
odd_matrix = odd_numbers.reshape(len(odd_numbers),1)
even_matrix = even_numbers.reshape(len(even_numbers),1)

In [219]:
product_matrix = np.dot(odd_matrix, even_matrix.T)

In [220]:
inverse_matrix = np.linalg.inv(product_matrix)

LinAlgError: ignored

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [179]:
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
